# Generated by Django 5.1 on 2024-08-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('position', models.IntegerField()),
                ('country', models.CharField(default='us', max_length=5)),
                ('language', models.CharField(default='en', max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
