# Generated by Django 5.1 on 2024-08-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
