# Generated by Django 5.1 on 2024-08-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_searchquery_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='accept_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
